#include <fstream>
using namespace std;
ifstream cin("interclasare.in");
ofstream cout("interclasare.out");
int a[20001],b[20001],c[20001],d[20001],v[20001],poz[20001],i,j,n,nr,p,m,mm,st,dr,k,s,x;
bool viz1[20001],viz2[20001];
int main()
{
    cin>>n;
    for(i=1;i<=n;i++)
    {
        cin>>c[i];
        v[i]=c[i];
    }
    cin>>mm;
    for(i=1;i<=mm;i++)
    {
        cin>>d[i];
    }
    k=0;
    for(i=1;i<=n;i++)
    {
        st=1;dr=k;p=0;
        while (st<=dr)
        {
            m=(st+dr)/2;
            if(c[i]<a[m])
            {
                p=m;
                dr=m-1;
            }
            else
            {
                st=m+1;
            }
        }
        if(p!=0)
        {
            a[p]=c[i];
            b[i]=p;
        }
        else
        {
            k++;
            a[k]=c[i];
            b[i]=k;
        }
    }
    s+=k;
    for(i=n;i>=1;i--)
    {
        if(b[i]==k)
        {
            viz1[i]=1;
            k--;
        }
    }
    for(i=1;i<=n;i++)
        a[i]=b[i]=0;
    k=0;
    for(i=1;i<=mm;i++)
    {
        st=1;dr=k;p=0;
        while (st<=dr)
        {
            m=(st+dr)/2;
            if(d[i]<a[m])
            {
                p=m;
                dr=m-1;
            }
            else
            {
                st=m+1;
            }
        }
        if(p!=0)
        {
            a[p]=d[i];
            b[i]=p;
        }
        else
        {
            k++;
            a[k]=d[i];
            b[i]=k;
        }
    }
    s+=k;
    for(i=mm;i>=1;i--)
    {
        if(b[i]==k)
        {
            viz2[i]=1;
            k--;
        }
    }
    cout<<s<<'\n';
    k=n;
    x=0;
    for(i=1;i<=n;i++)
        poz[i]=i;
    for(i=1;i<=mm;i++)
    {
        if(viz2[i]==1)
        {
            j=k;
            while((viz1[poz[j]]==0||d[i]<v[j])&&j>x)
            {
                v[j+1]=v[j];
                poz[j+1]=poz[j];
                j--;
            }
            v[j+1]=d[i];
            x=j+1;
            k++;
        }
        else
        {
            j=k;
            while(j>x)
            {
                v[j+1]=v[j];
                poz[j+1]=poz[j];
                j--;
            }
            v[j+1]=d[i];
            k++;
            x=j+1;
        }
    }
    for(i=1;i<=n+mm;i++)
        cout<<v[i]<<' ';
    return 0;
}
